language: objective-c
osx_image: xcode61
before_install: true
script:
    - cd Framework
    - cd CocoaAsyncSocket
    - xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO
    - xcodebuild -scheme 'CocoaAsyncSocket' test